name: Create Docker Image

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  PR_NUMBER: ${{ github.event.number }}
      
jobs:
  triage:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    
    - name: Fetch Label of PR
      id: label-the-PR
      run: |
        echo $PR_NUMBER
        PR_LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/labels" | jq -r '.[].name' | tr '\n' ',')
        echo "::set-output name=pr-labels::$PR_LABELS"

    - id: create-sushi-image
      if: contains(steps.label-the-PR.outputs.pr-labels, 'sushi')
      run: |
        echo "sushi found"
