name: Create Docker Image

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  PR_NUMBER: ${{ github.event.number }}
      
jobs:
  triage:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - id: create-sushi-image
      if: contains(github.event.pull_request.labels.*.name, 'sushi')
      run: |
        echo "sushi found"
